import 'package:major_project1/features/levels/Models/item_model.dart';

List<ItemModel> kHnAlphabets = [
  ItemModel(pnoun: 'A', value: '1', letter: 'अ'),
  ItemModel(pnoun: 'AA', value: '2', letter: 'आ'),
  ItemModel(pnoun: 'E', value: '3', letter: 'इ'),
  ItemModel(pnoun: 'EE', value: '4', letter: 'ई'),
  ItemModel(pnoun: 'U', value: '5', letter: 'उ'),
  ItemModel(pnoun: 'UU', value: '6', letter: 'ऊ'),
  ItemModel(pnoun: 'RI', value: '7', letter: 'ऋ'),
  ItemModel(pnoun: 'I', value: '8', letter: 'ए'),
  ItemModel(pnoun: 'IE', value: '9', letter: 'ऐ'),
  ItemModel(pnoun: 'O', value: '10', letter: 'ओ'),
  ItemModel(pnoun: 'OU', value: '11', letter: 'औ'),
  ItemModel(pnoun: 'AM', value: '12', letter: 'अं'),
  ItemModel(pnoun: 'AH', value: '13', letter: 'अः'),
  ItemModel(pnoun: 'KA', value: '14', letter: 'क'),
  ItemModel(pnoun: 'KHA', value: '15', letter: 'ख'),
  ItemModel(pnoun: 'GA', value: '16', letter: 'ग'),
  ItemModel(pnoun: 'GHA', value: '17', letter: 'घ'),
  ItemModel(pnoun: 'UNGA', value: '18', letter: 'ङ'),
  ItemModel(pnoun: 'CA', value: '19', letter: 'च'),
  ItemModel(pnoun: 'CHA', value: '20', letter: 'छ'),
  ItemModel(pnoun: 'JA', value: '21', letter: 'ज'),
  ItemModel(pnoun: 'JHA', value: '22', letter: 'झ'),
  ItemModel(pnoun: 'NYA', value: '23', letter: 'ञ'),
  ItemModel(pnoun: 'TA', value: '24', letter: 'ट'),
  ItemModel(pnoun: 'THA', value: '25', letter: 'ठ'),
  ItemModel(pnoun: 'DA', value: '26', letter: 'ड'),
  ItemModel(pnoun: 'DHA', value: '27', letter: 'ढ'),
  ItemModel(pnoun: 'uNA', value: '28', letter: 'ण'),
  ItemModel(pnoun: 'TA', value: '29', letter: 'त'),
  ItemModel(pnoun: 'THA', value: '30', letter: 'थ'),
  ItemModel(pnoun: 'DA', value: '31', letter: 'द'),
  ItemModel(pnoun: 'DHA', value: '32', letter: 'ध'),
  ItemModel(pnoun: 'NA', value: '33', letter: 'न'),
  ItemModel(pnoun: 'PA', value: '34', letter: 'प'),
  ItemModel(pnoun: 'PHA', value: '35', letter: 'फ'),
  ItemModel(pnoun: 'BA', value: '36', letter: 'ब'),
  ItemModel(pnoun: 'BHA', value: '37', letter: 'भ'),
  ItemModel(pnoun: 'MA', value: '38', letter: 'म'),
  ItemModel(pnoun: 'YA', value: '39', letter: 'य'),
  ItemModel(pnoun: 'RA', value: '40', letter: 'र'),
  ItemModel(pnoun: 'LA', value: '41', letter: 'ल'),
  ItemModel(pnoun: 'VA', value: '42', letter: 'व'),
  ItemModel(pnoun: 'SHA', value: '43', letter: 'श'),
  ItemModel(pnoun: 'SHHA', value: '44', letter: 'ष'),
  ItemModel(pnoun: 'SA', value: '45', letter: 'स'),
  ItemModel(pnoun: 'HA', value: '46', letter: 'ह'),
  ItemModel(pnoun: 'KSHA', value: '47', letter: 'क्ष'),
  ItemModel(pnoun: 'TRA', value: '48', letter: 'त्र'),
  ItemModel(pnoun: 'dNYA', value: '49', letter: 'ज्ञ'),
  ItemModel(pnoun: 'SHRA', value: '50', letter: 'श्र'),
];
List<ItemModel> kJpAlphabets = [
  ItemModel(pnoun: 'a', value: '1', letter: 'あ'),
  ItemModel(pnoun: 'i', value: '2', letter: 'い'),
  ItemModel(pnoun: 'u', value: '3', letter: 'う'),
  ItemModel(pnoun: 'e', value: '4', letter: 'え'),
  ItemModel(pnoun: 'o', value: '5', letter: 'お'),
  ItemModel(pnoun: 'ka', value: '6', letter: 'か'),
  ItemModel(pnoun: 'ki', value: '7', letter: 'き'),
  ItemModel(pnoun: 'ku', value: '8', letter: 'く'),
  ItemModel(pnoun: 'ke', value: '9', letter: 'け'),
  ItemModel(pnoun: 'ko', value: '10', letter: 'こ'),
  ItemModel(pnoun: 'sa', value: '11', letter: 'さ'),
  ItemModel(pnoun: 'shi', value: '12', letter: 'し'),
  ItemModel(pnoun: 'su', value: '13', letter: 'す'),
  ItemModel(pnoun: 'se', value: '14', letter: 'せ'),
  ItemModel(pnoun: 'so', value: '15', letter: 'そ'),
  ItemModel(pnoun: 'ta', value: '16', letter: 'た'),
  ItemModel(pnoun: 'chi', value: '17', letter: 'ち'),
  ItemModel(pnoun: 'tsu', value: '18', letter: 'つ'),
  ItemModel(pnoun: 'te', value: '19', letter: 'て'),
  ItemModel(pnoun: 'to', value: '20', letter: 'と'),
  ItemModel(pnoun: 'na', value: '21', letter: 'な'),
  ItemModel(pnoun: 'ni', value: '22', letter: 'に'),
  ItemModel(pnoun: 'nu', value: '23', letter: 'ぬ'),
  ItemModel(pnoun: 'ne', value: '24', letter: 'ね'),
  ItemModel(pnoun: 'no', value: '25', letter: 'の'),
  ItemModel(pnoun: 'ha', value: '26', letter: 'は'),
  ItemModel(pnoun: 'hi', value: '27', letter: 'ひ'),
  ItemModel(pnoun: 'fu', value: '28', letter: 'ふ'),
  ItemModel(pnoun: 'he', value: '29', letter: 'へ'),
  ItemModel(pnoun: 'ho', value: '30', letter: 'ほ'),
  ItemModel(pnoun: 'ma', value: '31', letter: 'ま'),
  ItemModel(pnoun: 'mi', value: '32', letter: 'み'),
  ItemModel(pnoun: 'mu', value: '33', letter: 'む'),
  ItemModel(pnoun: 'me', value: '34', letter: 'め'),
  ItemModel(pnoun: 'mo', value: '35', letter: 'も'),
  ItemModel(pnoun: 'ya', value: '36', letter: 'や'),
  ItemModel(pnoun: 'yu', value: '37', letter: 'ゆ'),
  ItemModel(pnoun: 'yo', value: '38', letter: 'よ'),
  ItemModel(pnoun: 'ra', value: '39', letter: 'ら'),
  ItemModel(pnoun: 'ri', value: '40', letter: 'り'),
  ItemModel(pnoun: 'ru', value: '41', letter: 'る'),
  ItemModel(pnoun: 're', value: '42', letter: 'れ'),
  ItemModel(pnoun: 'ro', value: '43', letter: 'ろ'),
  ItemModel(pnoun: 'v', value: '44', letter: 'ゔ'),
  ItemModel(pnoun: 'n', value: '45', letter: 'ん'),
  ItemModel(pnoun: 'wa', value: '46', letter: 'わ'),
  ItemModel(pnoun: 'wi', value: '47', letter: 'ゐ'),
  ItemModel(pnoun: 'we', value: '48', letter: 'ゑ'),
  ItemModel(pnoun: 'wo', value: '49', letter: 'を'),
  ItemModel(pnoun: 'ga', value: '51', letter: 'が'),
  ItemModel(pnoun: 'gi', value: '52', letter: 'ぎ'),
  ItemModel(pnoun: 'gu', value: '53', letter: 'ぐ'),
  ItemModel(pnoun: 'ge', value: '54', letter: 'げ'),
  ItemModel(pnoun: 'go', value: '55', letter: 'ご'),
  ItemModel(pnoun: 'za', value: '56', letter: 'ざ'),
  ItemModel(pnoun: 'ji', value: '57', letter: 'じ'),
  ItemModel(pnoun: 'zu', value: '58', letter: 'ず'),
  ItemModel(pnoun: 'ze', value: '59', letter: 'ぜ'),
  ItemModel(pnoun: 'zo', value: '60', letter: 'ぞ'),
  ItemModel(pnoun: 'da', value: '62', letter: 'だ'),
  ItemModel(pnoun: 'dji', value: '63', letter: 'ぢ'),
  ItemModel(pnoun: 'dzu', value: '64', letter: 'づ'),
  ItemModel(pnoun: 'de', value: '65', letter: 'で'),
  ItemModel(pnoun: 'do', value: '66', letter: 'ど'),
  ItemModel(pnoun: 'ba', value: '67', letter: 'ば'),
  ItemModel(pnoun: 'bi', value: '68', letter: 'び'),
  ItemModel(pnoun: 'bu', value: '69', letter: 'ぶ'),
  ItemModel(pnoun: 'be', value: '70', letter: 'べ'),
  ItemModel(pnoun: 'bo', value: '71', letter: 'ぼ'),
  ItemModel(pnoun: 'pa', value: '72', letter: 'ぱ'),
  ItemModel(pnoun: 'pi', value: '73', letter: 'ぴ'),
  ItemModel(pnoun: 'pu', value: '74', letter: 'ぷ'),
  ItemModel(pnoun: 'pe', value: '75', letter: 'ぺ'),
  ItemModel(pnoun: 'po', value: '76', letter: 'ぽ'),
];
List<ItemModel> kZhAlphabets = [
  ItemModel(pnoun: 'wǒ', value: '1', letter: '我'), // I, me
  ItemModel(pnoun: 'nǐ', value: '2', letter: '你'), // you
  ItemModel(pnoun: 'tā', value: '3', letter: '他'), // he
  ItemModel(pnoun: 'tā', value: '4', letter: '她'), // she
  ItemModel(pnoun: 'tā', value: '5', letter: '它'), // it
  ItemModel(pnoun: 'shì', value: '6', letter: '是'), // is / are / am
  ItemModel(pnoun: 'bù', value: '7', letter: '不'), // not
  ItemModel(pnoun: 'zài', value: '8', letter: '在'), // at / in
  ItemModel(pnoun: 'yǒu', value: '9', letter: '有'), // have
  ItemModel(pnoun: 'hǎo', value: '10', letter: '好'), // good
  ItemModel(pnoun: 'xiè', value: '11', letter: '谢'), // thank
  ItemModel(pnoun: 'zěnme', value: '12', letter: '怎么'), // how
  ItemModel(pnoun: 'shénme', value: '13', letter: '什么'), // what
  ItemModel(pnoun: 'nǎ', value: '14', letter: '哪'), // which
  ItemModel(pnoun: 'lái', value: '15', letter: '来'), // come
  ItemModel(pnoun: 'qù', value: '16', letter: '去'), // go
  ItemModel(pnoun: 'huí', value: '17', letter: '回'), // return
  ItemModel(pnoun: 'kàn', value: '18', letter: '看'), // look
  ItemModel(pnoun: 'tīng', value: '19', letter: '听'), // listen
  ItemModel(pnoun: 'shuō', value: '20', letter: '说'), // speak
  ItemModel(pnoun: 'chī', value: '21', letter: '吃'), // eat
  ItemModel(pnoun: 'hē', value: '22', letter: '喝'), // drink
  ItemModel(pnoun: 'mǎi', value: '23', letter: '买'), // buy
  ItemModel(pnoun: 'mài', value: '24', letter: '卖'), // sell
  ItemModel(pnoun: 'xǐhuān', value: '25', letter: '喜欢'), // like
  ItemModel(pnoun: 'ài', value: '26', letter: '爱'), // love
  ItemModel(pnoun: 'rén', value: '27', letter: '人'), // person
  ItemModel(pnoun: 'shū', value: '28', letter: '书'), // book
  ItemModel(pnoun: 'shuǐ', value: '29', letter: '水'), // water
  ItemModel(pnoun: 'mǐfàn', value: '30', letter: '米饭'), // rice
];
List<ItemModel> kKnAlphabets = [
  ItemModel(pnoun: 'A', value: '1', letter: 'ಅ'),
  ItemModel(pnoun: 'AA', value: '2', letter: 'ಆ'),
  ItemModel(pnoun: 'I', value: '3', letter: 'ಇ'),
  ItemModel(pnoun: 'EE', value: '4', letter: 'ಈ'),
  ItemModel(pnoun: 'U', value: '5', letter: 'ಉ'),
  ItemModel(pnoun: 'OO', value: '6', letter: 'ಊ'),
  ItemModel(pnoun: 'RU', value: '7', letter: 'ಋ'),
  ItemModel(pnoun: 'E', value: '8', letter: 'ಎ'),
  ItemModel(pnoun: 'EE', value: '9', letter: 'ಏ'),
  ItemModel(pnoun: 'AI', value: '10', letter: 'ಐ'),
  ItemModel(pnoun: 'O', value: '11', letter: 'ಒ'),
  ItemModel(pnoun: 'OO', value: '12', letter: 'ಓ'),
  ItemModel(pnoun: 'AU', value: '13', letter: 'ಔ'),
  ItemModel(pnoun: 'AM', value: '14', letter: 'ಅಂ'),
  ItemModel(pnoun: 'AHA', value: '15', letter: 'ಅಃ'),
  ItemModel(pnoun: 'KA', value: '16', letter: 'ಕ'),
  ItemModel(pnoun: 'KHA', value: '17', letter: 'ಖ'),
  ItemModel(pnoun: 'GA', value: '18', letter: 'ಗ'),
  ItemModel(pnoun: 'GHA', value: '19', letter: 'ಘ'),
  ItemModel(pnoun: 'NGA', value: '20', letter: 'ಙ'),
  ItemModel(pnoun: 'CHA', value: '21', letter: 'ಚ'),
  ItemModel(pnoun: 'CHHA', value: '22', letter: 'ಛ'),
  ItemModel(pnoun: 'JA', value: '23', letter: 'ಜ'),
  ItemModel(pnoun: 'JHA', value: '24', letter: 'ಝ'),
  ItemModel(pnoun: 'NYA', value: '25', letter: 'ಞ'),
  ItemModel(pnoun: 'TTA', value: '26', letter: 'ಟ'),
  ItemModel(pnoun: 'TTHA', value: '27', letter: 'ಠ'),
  ItemModel(pnoun: 'DDA', value: '28', letter: 'ಡ'),
  ItemModel(pnoun: 'DDHA', value: '29', letter: 'ಢ'),
  ItemModel(pnoun: 'NNA', value: '30', letter: 'ಣ'),
  ItemModel(pnoun: 'TA', value: '31', letter: 'ತ'),
  ItemModel(pnoun: 'THA', value: '32', letter: 'ಥ'),
  ItemModel(pnoun: 'DA', value: '33', letter: 'ದ'),
  ItemModel(pnoun: 'DHA', value: '34', letter: 'ಧ'),
  ItemModel(pnoun: 'NA', value: '35', letter: 'ನ'),
  ItemModel(pnoun: 'PA', value: '36', letter: 'ಪ'),
  ItemModel(pnoun: 'PHA', value: '37', letter: 'ಫ'),
  ItemModel(pnoun: 'BA', value: '38', letter: 'ಬ'),
  ItemModel(pnoun: 'BHA', value: '39', letter: 'ಭ'),
  ItemModel(pnoun: 'MA', value: '40', letter: 'ಮ'),
  ItemModel(pnoun: 'YA', value: '41', letter: 'ಯ'),
  ItemModel(pnoun: 'RA', value: '42', letter: 'ರ'),
  ItemModel(pnoun: 'LA', value: '43', letter: 'ಲ'),
  ItemModel(pnoun: 'VA', value: '44', letter: 'ವ'),
  ItemModel(pnoun: 'SHA', value: '45', letter: 'ಶ'),
  ItemModel(pnoun: 'SSHA', value: '46', letter: 'ಷ'),
  ItemModel(pnoun: 'SA', value: '47', letter: 'ಸ'),
  ItemModel(pnoun: 'HA', value: '48', letter: 'ಹ'),
  ItemModel(pnoun: 'LLA', value: '49', letter: 'ಳ'),
  ItemModel(pnoun: 'KSH', value: '50', letter: 'ಕ್ಷ'),
  ItemModel(pnoun: 'GYA', value: '51', letter: 'ಜ್ಞ'),
];
List<ItemModel> kTaAlphabets = [
  ItemModel(pnoun: 'A', value: '1', letter: 'அ'),
  ItemModel(pnoun: 'AA', value: '2', letter: 'ஆ'),
  ItemModel(pnoun: 'I', value: '3', letter: 'இ'),
  ItemModel(pnoun: 'EE', value: '4', letter: 'ஈ'),
  ItemModel(pnoun: 'U', value: '5', letter: 'உ'),
  ItemModel(pnoun: 'OO', value: '6', letter: 'ஊ'),
  ItemModel(pnoun: 'RU', value: '7', letter: '஋'),
  ItemModel(pnoun: 'E', value: '8', letter: 'எ'),
  ItemModel(pnoun: 'EE', value: '9', letter: 'ஏ'),
  ItemModel(pnoun: 'AI', value: '10', letter: 'ஐ'),
  ItemModel(pnoun: 'O', value: '11', letter: 'ஒ'),
  ItemModel(pnoun: 'OO', value: '12', letter: 'ஓ'),
  ItemModel(pnoun: 'AU', value: '13', letter: 'ஔ'),
  ItemModel(pnoun: 'KA', value: '14', letter: 'க'),
  ItemModel(pnoun: 'NGA', value: '15', letter: 'ங'),
  ItemModel(pnoun: 'CHA', value: '16', letter: 'ச'),
  ItemModel(pnoun: 'NYA', value: '17', letter: 'ஞ'),
  ItemModel(pnoun: 'TTA', value: '18', letter: 'ட'),
  ItemModel(pnoun: 'NNA', value: '19', letter: 'ண'),
  ItemModel(pnoun: 'TA', value: '20', letter: 'த'),
  ItemModel(pnoun: 'NA', value: '21', letter: 'ந'),
  ItemModel(pnoun: 'PA', value: '22', letter: 'ப'),
  ItemModel(pnoun: 'MA', value: '23', letter: 'ம'),
  ItemModel(pnoun: 'YA', value: '24', letter: 'ய'),
  ItemModel(pnoun: 'RA', value: '25', letter: 'ர'),
  ItemModel(pnoun: 'LA', value: '26', letter: 'ல'),
  ItemModel(pnoun: 'VA', value: '27', letter: 'வ'),
  ItemModel(pnoun: 'ZHA', value: '28', letter: 'ழ'),
  ItemModel(pnoun: 'LLA', value: '29', letter: 'ள'),
  ItemModel(pnoun: 'RRA', value: '30', letter: 'ற'),
  ItemModel(pnoun: 'NA2', value: '31', letter: 'ன'),
  ItemModel(pnoun: 'SHA', value: '32', letter: 'ஷ'),
  ItemModel(pnoun: 'SSA', value: '33', letter: 'ஸ'),
  ItemModel(pnoun: 'HA', value: '34', letter: 'ஹ'),
  ItemModel(pnoun: 'KSHA', value: '35', letter: 'க்ஷ'),
];
List<ItemModel> kTeAlphabets = [
  ItemModel(pnoun: 'A', value: '1', letter: 'అ'),
  ItemModel(pnoun: 'AA', value: '2', letter: 'ఆ'),
  ItemModel(pnoun: 'I', value: '3', letter: 'ఇ'),
  ItemModel(pnoun: 'EE', value: '4', letter: 'ఈ'),
  ItemModel(pnoun: 'U', value: '5', letter: 'ఉ'),
  ItemModel(pnoun: 'OO', value: '6', letter: 'ఊ'),
  ItemModel(pnoun: 'RU', value: '7', letter: 'ఋ'),
  ItemModel(pnoun: 'E', value: '8', letter: 'ఎ'),
  ItemModel(pnoun: 'EE', value: '9', letter: 'ఏ'),
  ItemModel(pnoun: 'AI', value: '10', letter: 'ఐ'),
  ItemModel(pnoun: 'O', value: '11', letter: 'ఒ'),
  ItemModel(pnoun: 'OO', value: '12', letter: 'ఓ'),
  ItemModel(pnoun: 'AU', value: '13', letter: 'ఔ'),
  ItemModel(pnoun: 'KA', value: '14', letter: 'క'),
  ItemModel(pnoun: 'KHA', value: '15', letter: 'ఖ'),
  ItemModel(pnoun: 'GA', value: '16', letter: 'గ'),
  ItemModel(pnoun: 'GHA', value: '17', letter: 'ఘ'),
  ItemModel(pnoun: 'NGA', value: '18', letter: 'ఙ'),
  ItemModel(pnoun: 'CHA', value: '19', letter: 'చ'),
  ItemModel(pnoun: 'CHHA', value: '20', letter: 'ఛ'),
  ItemModel(pnoun: 'JA', value: '21', letter: 'జ'),
  ItemModel(pnoun: 'JHA', value: '22', letter: 'ఝ'),
  ItemModel(pnoun: 'NYA', value: '23', letter: 'ఞ'),
  ItemModel(pnoun: 'TTA', value: '24', letter: 'ట'),
  ItemModel(pnoun: 'TTHA', value: '25', letter: 'ఠ'),
  ItemModel(pnoun: 'DDA', value: '26', letter: 'డ'),
  ItemModel(pnoun: 'DDHA', value: '27', letter: 'ఢ'),
  ItemModel(pnoun: 'NNA', value: '28', letter: 'ణ'),
  ItemModel(pnoun: 'TA', value: '29', letter: 'త'),
  ItemModel(pnoun: 'THA', value: '30', letter: 'థ'),
  ItemModel(pnoun: 'DA', value: '31', letter: 'ద'),
  ItemModel(pnoun: 'DHA', value: '32', letter: 'ధ'),
  ItemModel(pnoun: 'NA', value: '33', letter: 'న'),
  ItemModel(pnoun: 'PA', value: '34', letter: 'ప'),
  ItemModel(pnoun: 'PHA', value: '35', letter: 'ఫ'),
  ItemModel(pnoun: 'BA', value: '36', letter: 'బ'),
  ItemModel(pnoun: 'BHA', value: '37', letter: 'భ'),
  ItemModel(pnoun: 'MA', value: '38', letter: 'మ'),
  ItemModel(pnoun: 'YA', value: '39', letter: 'య'),
  ItemModel(pnoun: 'RA', value: '40', letter: 'ర'),
  ItemModel(pnoun: 'LA', value: '41', letter: 'ల'),
  ItemModel(pnoun: 'VA', value: '42', letter: 'వ'),
  ItemModel(pnoun: 'SHA', value: '43', letter: 'శ'),
  ItemModel(pnoun: 'SSHA', value: '44', letter: 'ష'),
  ItemModel(pnoun: 'SA', value: '45', letter: 'స'),
  ItemModel(pnoun: 'HA', value: '46', letter: 'హ'),
  ItemModel(pnoun: 'LLA', value: '47', letter: 'ళ'),
  ItemModel(pnoun: 'KSH', value: '48', letter: 'క్ష'),
  ItemModel(pnoun: 'GYA', value: '49', letter: 'జ్ఞ'),
];
